export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const LOG_EVENT = 'LOG_EVENT';
export const SETUP_DRIZZLE_STORE = 'SETUP_DRIZZLE_STORE';